require: rubocop-rails

AllCops:
  NewCops: enable 
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Bundler/OrderedGems:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
